### Get a list of  actions performed by a privileged account acting as privileged user given a period of time.

GET {{agentUrl}}/agent/v1/audittrail/privilegeduser
    ?startTimestamp=3
    &endTimestamp=3
    &before=1
    &after=10
    &limit=3
    &initiatorId=3
    &role=ADMINISTRATOR
sessionToken: {{sessionToken}}
keyManagerToken: {{keyManToken}}
Accept: application/json