### Sends an invitation to connect with another user

POST {{podUrl}}/pod/v1/connection/create
sessionToken: {{sessionToken}}
Accept: application/json
Content-Type: application/json

{
  "userId": 16
}