### [Admin] Add a member to an existing room.

POST {{podUrl}}/pod/v1/admin/room/id6/membership/add
sessionToken: {{sessionToken}}
Accept: application/json
Content-Type: application/json

{
  "id": 94
}