### Disables a policy.

POST {{agentUrl}}/agent/v1/dlp/policies/policyId31/disable
sessionToken: {{sessionToken}}
keyManagerToken: {{keyManToken}}
Accept: application/json
Content-Type: application/json

