### Override dictionary content with provided content.

POST {{agentUrl}}/agent/v1/dlp/dictionaries/dictId31/data/upload
sessionToken: {{sessionToken}}
keyManagerToken: {{keyManToken}}
Accept: application/json
Content-Type: application/json

