### Search for users by name or email address

POST {{podUrl}}/pod/v1/user/search
    ?skip=0
    &limit=32
    &local=false
sessionToken: {{sessionToken}}
Accept: application/json
Content-Type: application/json

{
  "query": "query36",
  "filters": {
    "title": "title36",
    "company": "company36",
    "location": "location36"
  }
}