### Unfollow users

POST {{podUrl}}/pod/v1/user/{{user_id}}/unfollow
    ?uid=16
    &email=email6
sessionToken: {{sessionToken}}
Accept: application/json
Content-Type: application/json

{
    "followers": [
        13056700579848,
        13056700580889,
        13056700580890
    ]
}